#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# scp syntax: scp [options] [source] [destination]
# For transfering file from local to remote:
    # scp -i "ssh" -o # "file" username@remote:/path/to/destination/

if [ $# -eq 4 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
