#!/usr/bin/env bash
# A Bash script to install nginx webserver

# Update the package manager to get least packages
apt-get update

# Installing nginx
apt-get install -y nginx

# Echo the string to be retrived using GET requist
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restarting Nginx web server to verify changes
service nginx restart