#!/usr/bin/env bash
#configure nginx server to listen for port 80 optimized
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"