#!/usr/bin/env bash
# Bash script that loops from 1 to 10 & display sentences

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]; then
        echo "bad luch"
    elif [ $counter -eq 7 ]; then
        echo "good luch"
    else
        echo "Best School"
    fi
    counter=$((counter+1))
done
