#!/usr/bin/env bash
# A bash Script that configures an Ubuntu server with the below requirements.

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Creates a backup file
cp /etc/hosts ~/hosts.new

# Configurations
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new

# Do the configs to the original file
cp -f ~/hosts.new /etc/hosts
